// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN3SZJkX4-I-E8UGr3yDsGhrIuq4xUNXQ',
    appId: '1:78526483336:web:91c3faeadd43e40b33483d',
    messagingSenderId: '78526483336',
    projectId: 'fir-flutter-codelab-b8832',
    authDomain: 'fir-flutter-codelab-b8832.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-b8832.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTmd9Gr1gDiP9sv9yx61ecGllUbxfdWTw',
    appId: '1:78526483336:android:fc8726b6fcf13a8a33483d',
    messagingSenderId: '78526483336',
    projectId: 'fir-flutter-codelab-b8832',
    storageBucket: 'fir-flutter-codelab-b8832.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk1JbSKH8X-eY8XFd9NMsZ03RiXg_GHy0',
    appId: '1:78526483336:ios:ababbe0585b0a77433483d',
    messagingSenderId: '78526483336',
    projectId: 'fir-flutter-codelab-b8832',
    storageBucket: 'fir-flutter-codelab-b8832.appspot.com',
    iosClientId: '78526483336-ilk9abq19c68hbmk925bnnusuufa5p06.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk1JbSKH8X-eY8XFd9NMsZ03RiXg_GHy0',
    appId: '1:78526483336:ios:ababbe0585b0a77433483d',
    messagingSenderId: '78526483336',
    projectId: 'fir-flutter-codelab-b8832',
    storageBucket: 'fir-flutter-codelab-b8832.appspot.com',
    iosClientId: '78526483336-ilk9abq19c68hbmk925bnnusuufa5p06.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
